[package]
name = "obj_2_rust"
description = "Macro to bring an obj file into rust"
license = "MIT"
version = "0.1.4"
edition = "2024"

[lib]
name = "obj_2_rust"
path = "src/lib.rs"
proc-macro = true

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = "2.0.101"
